# -*- coding: utf-8 -*-
"""dateset.py — Colab 원본 보관 (초기 데이터셋 생성기)

Automatically generated by Colab → downloaded as .py
Original: https://colab.research.google.com/drive/1N8_i2J_PMBkNh6tmArJ3SZbdmP7Sv5Tr

프로젝트 내 위치: scripts/colab/dateset.py (파일명 오타 dateset 유지)
본선 RAW 재생성: scripts/generate_rag_dataset.py
설명: scripts/colab/README.md

##1. 비정형 데이터
"""

# ==========================================
# PART 1. 비정형 데이터 (Unstructured Text)
# ==========================================
TARGET_DATE = "2024-07-29"

unstructured_text = f"""==================================================
[사건 관련자 종합 진술서 및 현장 조사 기록]
작성일자: {TARGET_DATE}
==================================================

1. 용의자 A (김팀장) 진술:
"어제 밤 11시부터 자정까지 내 자리에서 오늘 이사회 발표 기획서를 검토하고 있었다.
11시 반쯤 자판기에서 캔커피 하나 마신 것 외에는 계속 자리를 지켰다."

2. 용의자 B (이대리) 진술:
"밤 10시 30분에 업무를 마치고 11시부터 자정까지 탕비실에서 넷플릭스를 봤습니다.
서버실에 들어간 적도 없으며, 들어가려면 지문 로그가 남았을 겁니다."

3. 용의자 C (박신입) 진술:
"저녁에 먹은 마라탕 때문에 배탈이 나서 11시부터 계속 3층 화장실에 갇혀 있었습니다.
서버실 근처에는 지나가지도 않았습니다."

--------------------------------------------------
[포렌식 및 현장 수사관 종합 의견]
- 23:30 경 김팀장의 개인 PC 접속 기록은 없으나, 외부 결제 내역이 발견됨.
- 23:25 경 3층 탕비실 AP를 통한 100GB 규모의 외부 데이터 무단 전송 확인. (IP: 192.168.1.15)
- 박신입의 진술에 따르면 서버실에서 '기계식 청축 체리키보드' 타건 소리가 청취됨.
==================================================
"""

with open("1_unstructured_investigation.txt", "w", encoding="utf-8") as f:
    f.write(unstructured_text)

print("📄 [1/4] 비정형 데이터 (1_unstructured_investigation.txt) 생성 완료!")

"""##2. 반정형 데이터"""

# ==========================================
# PART 2. 반정형 데이터 (Semi-Structured JSON)
# ==========================================
import json
import random

TARGET_DATE = "2024-07-29"
slack_json_data = []

# (1) 일반 노이즈 메신저 대화 30건
dummy_chat = [
    ("김팀장", "이대리", "오늘 보고서 마무리됐나?"),
    ("이대리", "김팀장", "탕비실에서 검토 후 보내드리겠습니다."),
    ("박신입", "최동기", "오늘 점심 메뉴 추천받음")
]

for i in range(30):
    s, r, m = random.choice(dummy_chat)
    slack_json_data.append({
        "message_id": f"MSG_{i+1:03d}",
        "timestamp": f"{TARGET_DATE} {random.randint(9, 21):02d}:{random.randint(0, 59):02d}:00",
        "channel": "dev-team-chat",
        "sender": s,
        "receiver": r,
        "message": m
    })

# (2) ★ 단서 메신저 대화 주입
SLACK_EVIDENCE = [
    {"time": "22:45:10", "sender": "박신입", "receiver": "최동기", "msg": "아 배 아파... 저녁에 먹은 마라탕이 문제인가 ㅠㅠ"},
    {"time": "23:20:15", "sender": "박신입", "receiver": "최동기", "msg": "야 나 사실 서버실 구석에 숨어서 낮잠 자는 중 ㅋㅋ"},
    {"time": "23:26:40", "sender": "박신입", "receiver": "최동기", "msg": "헉 미친... 누가 들어와서 키보드 치는데 이대리님 청축 체리키보드 소리임 ㄷㄷ"}
]

for idx, item in enumerate(SLACK_EVIDENCE):
    slack_json_data.append({
        "message_id": f"EV_MSG_{idx+1:03d}",
        "timestamp": f"{TARGET_DATE} {item['time']}",
        "channel": "dev-team-private",
        "sender": item["sender"],
        "receiver": item["receiver"],
        "message": item["msg"]
    })

with open("2_semistructured_slack.json", "w", encoding="utf-8") as f:
    json.dump(slack_json_data, f, ensure_ascii=False, indent=2)

print("💬 [2/4] 반정형 데이터 (2_semistructured_slack.json) 생성 완료!")

"""## 3. 정형 데이터"""

# ==========================================
# PART 3. 정형 데이터 (Structured CSV)
# ==========================================
import csv
import random

TARGET_DATE = "2024-07-29"
csv_rows = [["Transaction_ID", "Date", "Time", "Card_Owner", "Merchant_Name", "Amount", "Category", "Status"]]

# (1) 일반 노이즈 카드 결제 50건
merchants = [("스타벅스", 12000, "식대"), ("한일관", 45000, "식대"), ("카카오T", 15000, "교통비")]
owners = ["김팀장", "이대리", "박신입", "최동기"]

for i in range(50):
    m_name, amt, cat = random.choice(merchants)
    csv_rows.append([
        f"TX_{i+1000}",
        TARGET_DATE,
        f"{random.randint(8, 20):02d}:{random.randint(0, 59):02d}:00",
        random.choice(owners),
        m_name,
        amt,
        cat,
        "승인"
    ])

# (2) ★ 단서 카드 결제 주입 (김팀장 알리바이 격파용)
CARD_EVIDENCE = [
    [TARGET_DATE, "23:30:45", "김팀장", "강남역 로맨스 룸살롱", "850000", "접대비", "승인"],
    [TARGET_DATE, "00:12:00", "김팀장", "카카오T 택시", "24500", "교통비", "승인"]
]

for idx, row in enumerate(CARD_EVIDENCE):
    csv_rows.append([f"EV_TX_{idx+1:03d}"] + row)

with open("3_structured_corporate_card.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerows(csv_rows)

print("📊 [3/4] 정형 데이터 (3_structured_corporate_card.csv) 생성 완료!")

"""## 4. 시스템 로그 데이터"""

# ==========================================
# PART 4. 시스템 로그 데이터 (System Logs)
# ==========================================
import random

TARGET_DATE = "2024-07-29"
sys_logs = []

# (1) 일반 노이즈 서버 로그 80건
for i in range(80):
    t = f"{TARGET_DATE} {random.randint(18, 22):02d}:{random.randint(0, 59):02d}:{random.randint(0, 59):02d}"
    sys_logs.append(f"[{t}] [INFO] Normal health check ping from AP-Zone-0{random.randint(1,4)} - 200 OK\n")

# (2) ★ 단서 로그 주입 (이대리 도용 및 외부 유출 흔적)
SYSTEM_LOG_EVIDENCE = [
    f"[{TARGET_DATE} 22:55:01] [AUTH_SUCCESS] User: '이대리' logged in via Terminal-04 (IP: 192.168.1.42)\n",
    f"[{TARGET_DATE} 23:10:00] [DOOR_ACCESS] Door: 'Server Room Main' - Tagged by: '김팀장 (Card_ID: EMP-001)'\n",
    f"[{TARGET_DATE} 23:25:01] [NET_TRANSFER] Source_IP: 192.168.1.15 (AP-Breakroom-02 / MAC: 00:1A:2B:3C:4D:5E) -> Target: 185.220.101.5 / File: omega_model_weights.bin (102.4 GB) / Status: COMPLETED\n"
]

sys_logs.extend(SYSTEM_LOG_EVIDENCE)

with open("4_system_access_log.txt", "w", encoding="utf-8") as f:
    f.writelines(sys_logs)

print("🖥️ [4/4] 시스템 로그 데이터 (4_system_access_log.txt) 생성 완료!")

"""## 5. RAGVector DB 적재 + Router + LangGraph State 통합 백엔드"""

# ==========================================
# PART 5. 데이터셋 Vector DB 적재 및 검색 라우터 (기초 엔진)
# ==========================================
import os
import json
import csv

# 1. 필요 패키지 설치
!pip install -q chromadb sentence-transformers

import chromadb
from chromadb.utils import embedding_functions

print("⚡ [Data Engine] Vector DB 구축 및 통합 검색 엔진 초기화 중...\n")

# 2. Vector DB (ChromaDB) 클라이언트 설정
chroma_client = chromadb.Client()
default_ef = embedding_functions.DefaultEmbeddingFunction()

# 기존 DB 초기화 (중복 방지)
try:
    chroma_client.delete_collection("game_evidence_db")
except:
    pass

evidence_collection = chroma_client.create_collection(
    name="game_evidence_db",
    embedding_function=default_ef
)

# ------------------------------------------------------------------------------
# [A] 4대 데이터셋 로드 및 DB 인덱싱 (Indexing)
# ------------------------------------------------------------------------------
docs_to_add = []
metadatas_to_add = []
ids_to_add = []
doc_id_count = 1

# A-1. 비정형 데이터 적재 (1_unstructured_investigation.txt)
if os.path.exists("1_unstructured_investigation.txt"):
    with open("1_unstructured_investigation.txt", "r", encoding="utf-8") as f:
        chunks = [c.strip() for c in f.read().split("\n\n") if c.strip()]
        for chunk in chunks:
            docs_to_add.append(chunk)
            metadatas_to_add.append({"source": "unstructured_txt", "type": "unstructured"})
            ids_to_add.append(f"DOC_{doc_id_count:04d}")
            doc_id_count += 1

# A-2. 반정형 데이터 적재 (2_semistructured_slack.json)
if os.path.exists("2_semistructured_slack.json"):
    with open("2_semistructured_slack.json", "r", encoding="utf-8") as f:
        slack_data = json.load(f)
        for msg in slack_data:
            formatted_msg = f"[{msg['timestamp']}] {msg['sender']} -> {msg['receiver']}: {msg['message']}"
            docs_to_add.append(formatted_msg)
            metadatas_to_add.append({"source": "slack_json", "type": "semistructured", "sender": msg["sender"]})
            ids_to_add.append(f"DOC_{doc_id_count:04d}")
            doc_id_count += 1

# A-3. 정형 데이터 적재 (3_structured_corporate_card.csv)
if os.path.exists("3_structured_corporate_card.csv"):
    with open("3_structured_corporate_card.csv", "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            formatted_card = f"[{row['Date']} {row['Time']}] 카드소유자: {row['Card_Owner']} / 가맹점: {row['Merchant_Name']} / 금액: {row['Amount']}원 ({row['Category']})"
            docs_to_add.append(formatted_card)
            metadatas_to_add.append({"source": "card_csv", "type": "structured", "owner": row['Card_Owner']})
            ids_to_add.append(f"DOC_{doc_id_count:04d}")
            doc_id_count += 1

# A-4. 시스템 로그 적재 (4_system_access_log.txt)
if os.path.exists("4_system_access_log.txt"):
    with open("4_system_access_log.txt", "r", encoding="utf-8") as f:
        for log in f.readlines():
            if log.strip():
                docs_to_add.append(log.strip())
                metadatas_to_add.append({"source": "system_log", "type": "log"})
                ids_to_add.append(f"DOC_{doc_id_count:04d}")
                doc_id_count += 1

# Vector DB 저장
if docs_to_add:
    evidence_collection.add(
        documents=docs_to_add,
        metadatas=metadatas_to_add,
        ids=ids_to_add
    )
    print(f"✅ 총 {len(docs_to_add)}개의 데이터 Chunk가 Vector DB에 성공적으로 적재되었습니다!")

# ------------------------------------------------------------------------------
# [B] 범용 데이터 검색 라우터 함수 (Retrieval Engine)
# ------------------------------------------------------------------------------
def search_dataset(query: str, data_type: str = "all", top_k: int = 3):
    """
    원하는 데이터 유형(data_type)별로 Vector DB에서 팩트를 조회하는 검색 함수
    - data_type 옵션: 'all', 'structured', 'semistructured', 'unstructured', 'log'
    """
    if data_type != "all":
        results = evidence_collection.query(
            query_texts=[query],
            n_results=top_k,
            where={"type": data_type}
        )
    else:
        results = evidence_collection.query(
            query_texts=[query],
            n_results=top_k
        )

    return results['documents'][0] if results['documents'] else []

print("🚀 데이터 엔진 준비 완료. 이제 어떤 상황(시나리오)이든 데이터를 투입하고 조회할 수 있습니다.")

"""## 상황 만들기 10개"""

# ==============================================================================
# [전 데이터 CSV 포맷 변환] 10개 추리 사건 통합 데이터셋 자동 생성기
# ==============================================================================
import csv
import random

# ------------------------------------------------------------------------------
# 1. 10가지 사건 메타데이터 및 스모킹 건 정의 (Truth Matrix Data)
# ------------------------------------------------------------------------------
CASES_DATABASE = {
    "case_01": {
        "title": "오메가 모델 가중치 무단 유출",
        "date": "2024-07-29",
        "unstructured_report": "23:30 경 김팀장 PC 작업 기록 없음. 23:25 탕비실 AP에서 100GB 외부 전송 확인. 박신입 증언: 서버실에서 청축 체리키보드 소리 청취.",
        "slack_evidence": [
            ["2024-07-29", "22:45:10", "박신입", "최동기", "아 배 아파... 저녁에 먹은 마라탕이 문제인가 ㅠㅠ"],
            ["2024-07-29", "23:20:15", "박신입", "최동기", "야 나 사실 서버실 구석에 숨어서 낮잠 자는 중 ㅋㅋ"],
            ["2024-07-29", "23:26:40", "박신입", "최동기", "헉 미친... 누가 들어와서 키보드 치는데 이대리님 청축 체리키보드 소리임 ㄷㄷ"]
        ],
        "card_evidence": [
            ["2024-07-29", "23:30:45", "김팀장", "강남역 로맨스 룸살롱", "850000", "접대비", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "22:55:01", "AUTH_SUCCESS", "Terminal-04", "이대리", "192.168.1.42", "Normal Login"],
            ["2024-07-29", "23:10:00", "DOOR_ACCESS", "Server Room Main", "김팀장", "192.168.1.1", "Tagged by Card_ID: EMP-001"],
            ["2024-07-29", "23:25:01", "NET_TRANSFER", "AP-Breakroom-02", "이대리", "192.168.1.15", "Transferred omega_model_weights.bin (102.4 GB) to 185.220.101.5"]
        ]
    },
    "case_02": {
        "title": "신약 레시피 무단 매각",
        "date": "2024-07-29",
        "unstructured_report": "이대리는 22:00 도서관 이용 기록 확인됨. 박신입은 팀장님 연구실 USB 복사 목격. 김팀장 22:40 시흥 낚시터 결제.",
        "slack_evidence": [
            ["2024-07-29", "21:30:00", "박신입", "최동기", "야 아까 팀장님 자리 지나가는데 연구소 백신 파일 USB에 복사하고 계시더라 ㄷㄷ"]
        ],
        "card_evidence": [
            ["2024-07-29", "22:40:15", "김팀장", "시흥 밤낚시터", "120000", "취미", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "21:25:00", "USB_MOUNT", "Terminal-01", "김팀장", "192.168.1.10", "Device: SanDisk_32GB Mounted"]
        ]
    },
    "case_03": {
        "title": "법인카드 5천만 원 대규모 횡령",
        "date": "2024-07-29",
        "unstructured_report": "김팀장 사촌 동생 명의 사업장으로 가짜 비품 결제 승인 유도 정황 포착.",
        "slack_evidence": [
            ["2024-07-29", "15:20:00", "이대리", "박신입", "팀장님이 친척 가게 상호로 결제하라고 강요하시는데 이거 감사 걸리면 어쩌냐..."]
        ],
        "card_evidence": [
            ["2024-07-29", "16:00:00", "김팀장", "(주)성태유통(사촌동생가게)", "50000000", "비품구입", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "16:05:00", "ERP_UPDATE", "ERP System", "김팀장", "192.168.1.10", "Invoice #9942 Approved"]
        ]
    },
    "case_04": {
        "title": "임원진 연봉 기밀표 유출",
        "date": "2024-07-29",
        "unstructured_report": "이대리 18:05 지하철 승차 기록 확인. 박신입 IP로 익명 커뮤니티 블라인드 접속 로그 포착.",
        "slack_evidence": [
            ["2024-07-29", "17:40:00", "박신입", "최동기", "동기야 헐... 나 아까 인사팀 공용 폴더 들어갔다가 연봉 파일 실수로 캡처함 ㄷㄷ"]
        ],
        "card_evidence": [
            ["2024-07-29", "18:05:00", "이대리", "지하철 2호선 테헤란로", "1400", "교통비", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "19:10:00", "POST_UPLOAD", "External Net", "박신입", "192.168.1.88", "Uploaded File to blind.kr"]
        ]
    },
    "case_05": {
        "title": "전기차 배터리 설계도 파괴",
        "date": "2024-07-29",
        "unstructured_report": "이대리 터미널에서 rm -rf 삭제 명령 포착. 박신입 퇴근 버스 태깅 시간 일치.",
        "slack_evidence": [
            ["2024-07-29", "18:30:00", "이대리", "최동기", "나 이직 확정됐다 ㅋㅋ 퇴근 전에 파일 정리나 깔끔하게 하고 가야지"]
        ],
        "card_evidence": [
            ["2024-07-29", "18:20:00", "박신입", "서울시 시내버스", "1500", "교통비", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "18:50:00", "CMD_EXEC", "Terminal-04", "이대리", "192.168.1.42", "Executed: rm -rf /project_battery"]
        ]
    },
    "case_06": {
        "title": "CEO 사칭 스피어 피싱 2억 유출",
        "date": "2024-07-29",
        "unstructured_report": "CEO 메일 핑 헤더 위조 발신자는 이대리 터미널. 이대리 해외 가상화폐 거래소 결제 내역 감지.",
        "slack_evidence": [
            ["2024-07-29", "14:10:00", "이대리", "최동기", "팀장님 메일 가짜로 보냈는데 속으시네 ㅋㅋ 2억 송금 승인 완료됨"]
        ],
        "card_evidence": [
            ["2024-07-29", "15:00:00", "이대리", "Binance Crypto", "1000000", "기타", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "14:00:00", "SMTP_SPOOF", "Mail Server", "이대리", "192.168.1.42", "Spoofed CEO Mail Sent to 김팀장"]
        ]
    },
    "case_07": {
        "title": "해커톤 제출작 소스코드 도용",
        "date": "2024-07-29",
        "unstructured_report": "박신입 GitHub 3주 전 커밋 이력 확인. 김팀장 계정 전날 박신입 레포지토리 clone 기록 감지.",
        "slack_evidence": [
            ["2024-07-29", "11:00:00", "김팀장", "이대리", "신입이 코드 기발하네. 이거 가져다가 내 이름으로 제출해야겠다 ㅋ"]
        ],
        "card_evidence": [
            ["2024-07-29", "12:00:00", "박신입", "김밥천국", "8000", "식대", "승인"]
        ],
        "log_evidence": [
            ["2024-07-28", "23:00:00", "GIT_CLONE", "Git Server", "김팀장", "192.168.1.10", "Cloned repo: park_hackathon"]
        ]
    },
    "case_08": {
        "title": "고객 정보 10만 건 텔레그램 판매",
        "date": "2024-07-29",
        "unstructured_report": "이대리 PC 메모장에서 DB 암호 발견. 텔레그램 API 통신 로깅 잡힘.",
        "slack_evidence": [
            ["2024-07-29", "16:20:00", "이대리", "최동기", "야 텔레그램 입금 확인됐다 10만 건 완료 ㅋㅋㅋ"]
        ],
        "card_evidence": [
            ["2024-07-29", "17:00:00", "이대리", "카카오T 택시", "18000", "교통비", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "16:15:00", "NET_OUTBOUND", "Firewall", "이대리", "192.168.1.42", "45MB Transferred to api.telegram.org"]
        ]
    },
    "case_09": {
        "title": "신제품 공작 찌라시 영상 유포",
        "date": "2024-07-29",
        "unstructured_report": "박신입 헬스장 결제 실패(잔액부족). 탕비실 IP에서 인스타그램 부계정 접속 영상 업로드 포착.",
        "slack_evidence": [
            ["2024-07-29", "20:10:00", "박신입", "최동기", "인스타 찌라시 올림 ㅋㅋㅋ 조회수 터지는 중"]
        ],
        "card_evidence": [
            ["2024-07-29", "19:00:00", "박신입", "스포애니 헬스장", "0", "식대", "거절"]
        ],
        "log_evidence": [
            ["2024-07-29", "20:05:00", "HTTP_POST", "Web Gateway", "박신입", "192.168.1.15", "Uploaded File to instagram.com"]
        ]
    },
    "case_10": {
        "title": "중앙 서버 랜섬웨어 감염 사고",
        "date": "2024-07-29",
        "unstructured_report": "김팀장 웹 브라우저 히스토리 토렌트 다운로드 감염. 슬랙으로 당황한 질문 포착.",
        "slack_evidence": [
            ["2024-07-29", "17:00:00", "김팀장", "이대리", "이대리야... 내 컴에 영화 다운받았는데 갑자기 파일 다 잠김 ㄷㄷ 어떡하냐"]
        ],
        "card_evidence": [
            ["2024-07-29", "12:30:00", "김팀장", "한일관", "35000", "식대", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "16:45:00", "MALWARE_DETECT", "Endpoint Sec", "김팀장", "192.168.1.10", "Ransomware executed via movie_torrent.exe"]
        ]
    }
}

# ------------------------------------------------------------------------------
# 2. 지정된 사건(case_id)에 맞게 4대 ALL-CSV 데이터셋 생성 파이프라인
# ------------------------------------------------------------------------------
def generate_all_csv_dataset(case_id="case_01"):
    if case_id not in CASES_DATABASE:
        print(f"❌ [에러] {case_id}는 존재하지 않는 사건입니다.")
        return

    case_info = CASES_DATABASE[case_id]
    target_date = case_info["date"]
    print(f"🎬 [{case_id.upper()}] '{case_info['title']}' ALL-CSV 데이터셋 자동 생성 시작...")

    # (1) 비정형/보고서 CSV 생성 (1_unstructured_investigation.csv)
    unstructured_rows = [
        ["Category", "Subject", "Content"],
        ["Overview", "사건명", case_info['title']],
        ["Overview", "사건일자", target_date],
        ["Alibi", "김팀장 진술", "어제 내 자리에서 야근하며 내일 회의 기획서를 보고 있었다."],
        ["Alibi", "이대리 진술", "업무 마치고 탕비실에서 휴식을 취하고 있었습니다."],
        ["Alibi", "박신입 진술", "배탈이 나서 화장실에 갇혀 있었습니다."],
        ["Investigation", "수사관 의견", case_info['unstructured_report']]
    ]
    with open("1_unstructured_investigation.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(unstructured_rows)

    # (2) 슬랙 대화록 CSV 생성 (2_semistructured_slack.csv)
    slack_rows = [["Date", "Time", "Sender", "Receiver", "Message"]]
    dummy_chat = [("김팀장", "이대리", "오늘 업무 완료됐나?"), ("이대리", "김팀장", "검토 중입니다."), ("박신입", "최동기", "점심 뭐 먹나요")]
    for _ in range(30):
        s, r, m = random.choice(dummy_chat)
        slack_rows.append([target_date, f"{random.randint(9, 21):02d}:{random.randint(0, 59):02d}:00", s, r, m])
    for row in case_info["slack_evidence"]:
        slack_rows.append(row)
    with open("2_semistructured_slack.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(slack_rows)

    # (3) 법인카드 CSV 생성 (3_structured_corporate_card.csv)
    card_rows = [["Date", "Time", "Card_Owner", "Merchant_Name", "Amount", "Category", "Status"]]
    for _ in range(50):
        card_rows.append([target_date, f"{random.randint(8, 20):02d}:{random.randint(0, 59):02d}:00", random.choice(["김팀장", "이대리", "박신입"]), "스타벅스", "12000", "식대", "승인"])
    for row in case_info["card_evidence"]:
        card_rows.append(row)
    with open("3_structured_corporate_card.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(card_rows)

    # (4) 시스템 로그 CSV 생성 (4_system_access_log.csv)
    log_rows = [["Date", "Time", "Event_Type", "Location", "User_Name", "IP_Address", "Detail_Log"]]
    for _ in range(80):
        log_rows.append([target_date, f"{random.randint(18, 22):02d}:{random.randint(0, 59):02d}:00", "HEALTH_CHECK", "Server_Room", "System", "192.168.1.1", "Normal ping check - 200 OK"])
    for row in case_info["log_evidence"]:
        log_rows.append(row)
    with open("4_system_access_log.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(log_rows)

    print(f"✅ [{case_id.upper()}] 4개 파일이 모두 CSV 포맷으로 완벽히 토출되었습니다!\n")

# ------------------------------------------------------------------------------
# [실행] 원하는 사건 번호 지정 (Case 01 ~ Case 10 가능)
# ------------------------------------------------------------------------------
generate_all_csv_dataset("case_01")

"""## Vector DB (ChromaDB) 적재 및 검색 라우터"""

import os
import csv
import chromadb
from chromadb.utils import embedding_functions

chroma_client = chromadb.Client()
default_ef = embedding_functions.DefaultEmbeddingFunction()

try:
    chroma_client.delete_collection("game_evidence_db")
except:
    pass

evidence_collection = chroma_client.create_collection(
    name="game_evidence_db",
    embedding_function=default_ef
)

docs_to_add, metadatas_to_add, ids_to_add = [], [], []
doc_id_count = 1

# CSV 파일들을 순회하며 DB에 적재
csv_files = [
    ("1_unstructured_investigation.csv", "unstructured"),
    ("2_semistructured_slack.csv", "semistructured"),
    ("3_structured_corporate_card.csv", "structured"),
    ("4_system_access_log.csv", "log")
]

for filename, data_type in csv_files:
    if os.path.exists(filename):
        with open(filename, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            header = next(reader)
            for row in reader:
                formatted_doc = f"[{data_type.upper()}] " + " | ".join(row)
                docs_to_add.append(formatted_doc)
                metadatas_to_add.append({"source": filename, "type": data_type})
                ids_to_add.append(f"DOC_{doc_id_count:04d}")
                doc_id_count += 1

if docs_to_add:
    evidence_collection.add(
        documents=docs_to_add,
        metadatas=metadatas_to_add,
        ids=ids_to_add
    )
    print(f"✅ 총 {len(docs_to_add)}개의 CSV 데이터 Chunk가 Vector DB에 적재되었습니다!")

# RAG 검색 함수
def search_dataset(query: str, data_type: str = "all", top_k: int = 3):
    if data_type != "all":
        results = evidence_collection.query(
            query_texts=[query], n_results=top_k, where={"type": data_type}
        )
    else:
        results = evidence_collection.query(
            query_texts=[query], n_results=top_k
        )
    return results['documents'][0] if results['documents'] else []

"""## 100개 이상 노이즈가 섞인 ALL-CSV 데이터 생성기"""

# ==============================================================================
# [노션 가이드 준수] 대용량 노이즈(90%) + 스모킹건(10%) ALL-CSV 생성기
# ==============================================================================
import csv
import random

# 10개 사건 메타데이터 (기존 데이터 유지)
CASES_DATABASE = {
    "case_01": {
        "title": "오메가 모델 가중치 무단 유출",
        "date": "2024-07-29",
        "unstructured_report": "23:30 경 김팀장 PC 작업 기록 없음. 23:25 탕비실 AP에서 100GB 외부 전송 확인. 박신입 증언: 서버실에서 청축 체리키보드 소리 청취.",
        "slack_evidence": [
            ["2024-07-29", "22:45:10", "박신입", "최동기", "아 배 아파... 저녁에 먹은 마라탕이 문제인가 ㅠㅠ"],
            ["2024-07-29", "23:20:15", "박신입", "최동기", "야 나 사실 서버실 구석에 숨어서 낮잠 자는 중 ㅋㅋ"],
            ["2024-07-29", "23:26:40", "박신입", "최동기", "헉 미친... 누가 들어와서 키보드 치는데 이대리님 청축 체리키보드 소리임 ㄷㄷ"]
        ],
        "card_evidence": [
            ["2024-07-29", "23:30:45", "김팀장", "강남역 로맨스 룸살롱", "850000", "접대비", "승인"]
        ],
        "log_evidence": [
            ["2024-07-29", "22:55:01", "AUTH_SUCCESS", "Terminal-04", "이대리", "192.168.1.42", "Normal Login"],
            ["2024-07-29", "23:10:00", "DOOR_ACCESS", "Server Room Main", "김팀장", "192.168.1.1", "Tagged by Card_ID: EMP-001"],
            ["2024-07-29", "23:25:01", "NET_TRANSFER", "AP-Breakroom-02", "이대리", "192.168.1.15", "Transferred omega_model_weights.bin (102.4 GB) to 185.220.101.5"]
        ]
    }
    # case_02 ~ case_10 동일 구조 적용
}

def generate_large_csv_dataset(case_id="case_01"):
    case_info = CASES_DATABASE[case_id]
    target_date = case_info["date"]
    print(f"🎬 [{case_id.upper()}] 노이즈 90% 포함 ALL-CSV 데이터셋 생성 중...")

    # 1. 진술서 CSV
    unstructured_rows = [
        ["Category", "Subject", "Content"],
        ["Overview", "사건명", case_info['title']],
        ["Overview", "사건일자", target_date],
        ["Alibi", "김팀장 진술", "어제 내 자리에서 야근하며 내일 회의 기획서를 보고 있었다."],
        ["Alibi", "이대리 진술", "업무 마치고 탕비실에서 휴식을 취하고 있었습니다."],
        ["Alibi", "박신입 진술", "배탈이 나서 화장실에 갇혀 있었습니다."],
        ["Investigation", "수사관 의견", case_info['unstructured_report']]
    ]
    with open("1_unstructured_investigation.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(unstructured_rows)

    # 2. 메신저 CSV (노이즈 100건 생성)
    slack_rows = [["Date", "Time", "Sender", "Receiver", "Message"]]
    dummy_chat = [("김팀장", "이대리", "오늘 보고서 마무리됐나?"), ("이대리", "김팀장", "검토 후 올려드리겠습니다."), ("박신입", "최동기", "점심 제육 먹으러 가실 분")]
    for _ in range(100):
        s, r, m = random.choice(dummy_chat)
        slack_rows.append([target_date, f"{random.randint(9, 21):02d}:{random.randint(0, 59):02d}:00", s, r, m])
    for row in case_info["slack_evidence"]:
        slack_rows.append(row)
    with open("2_semistructured_slack.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(slack_rows)

    # 3. 법인카드 CSV (노이즈 100건 생성)
    card_rows = [["Date", "Time", "Card_Owner", "Merchant_Name", "Amount", "Category", "Status"]]
    for _ in range(100):
        card_rows.append([target_date, f"{random.randint(8, 20):02d}:{random.randint(0, 59):02d}:00", random.choice(["김팀장", "이대리", "박신입"]), "스타벅스", "12000", "식대", "승인"])
    for row in case_info["card_evidence"]:
        card_rows.append(row)
    with open("3_structured_corporate_card.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(card_rows)

    # 4. 시스템 로그 CSV (노이즈 150건 생성)
    log_rows = [["Date", "Time", "Event_Type", "Location", "User_Name", "IP_Address", "Detail_Log"]]
    for _ in range(150):
        log_rows.append([target_date, f"{random.randint(18, 22):02d}:{random.randint(0, 59):02d}:00", "HEALTH_CHECK", "Server_Room", "System", "192.168.1.1", "Normal ping check - 200 OK"])
    for row in case_info["log_evidence"]:
        log_rows.append(row)
    with open("4_system_access_log.csv", "w", newline="", encoding="utf-8") as f:
        csv.writer(f).writerows(log_rows)

    print("✅ 4개 대용량 CSV 파일 생성 완료!\n")

generate_large_csv_dataset("case_01")

"""## ALL-CSV 인덱싱 및 RAG 검색 함수"""

# ==============================================================================
# [Vector DB Engine] 4개 CSV 통합 인덱싱 및 RAG 검색 라우터
# ==============================================================================
import os
import csv
import chromadb
from chromadb.utils import embedding_functions

chroma_client = chromadb.Client()
default_ef = embedding_functions.DefaultEmbeddingFunction()

try:
    chroma_client.delete_collection("game_evidence_db")
except:
    pass

evidence_collection = chroma_client.create_collection(
    name="game_evidence_db",
    embedding_function=default_ef
)

docs_to_add, metadatas_to_add, ids_to_add = [], [], []
doc_id_count = 1

csv_files = [
    ("1_unstructured_investigation.csv", "unstructured"),
    ("2_semistructured_slack.csv", "semistructured"),
    ("3_structured_corporate_card.csv", "structured"),
    ("4_system_access_log.csv", "log")
]

for filename, data_type in csv_files:
    if os.path.exists(filename):
        with open(filename, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            header = next(reader)
            for row in reader:
                formatted_doc = f"[{data_type.upper()}] " + " | ".join(row)
                docs_to_add.append(formatted_doc)
                metadatas_to_add.append({"source": filename, "type": data_type})
                ids_to_add.append(f"DOC_{doc_id_count:04d}")
                doc_id_count += 1

if docs_to_add:
    evidence_collection.add(
        documents=docs_to_add,
        metadatas=metadatas_to_add,
        ids=ids_to_add
    )
    print(f"✅ 총 {len(docs_to_add)}개의 CSV 데이터 Chunk가 Vector DB에 적재되었습니다!")

# RAG 검색 함수
def search_dataset(query: str, data_type: str = "all", top_k: int = 3):
    if data_type != "all":
        results = evidence_collection.query(
            query_texts=[query], n_results=top_k, where={"type": data_type}
        )
    else:
        results = evidence_collection.query(
            query_texts=[query], n_results=top_k
        )
    return results['documents'][0] if results['documents'] else []

"""프롬프트 템플릿 출력 & 데이터셋 검수 셀"""

# # ==============================================================================
# # [팀원 공유용] 대용량 노이즈 생성 프롬프트 템플릿 & 데이터셋 검수기
# # ==============================================================================

# print("📋 [팀원 공유용 LLM 프롬프트 템플릿]")
# print("========================================================================\n")

# print("1️⃣ [사내 메신저 Slack 노이즈 프롬프트]")
# print("""
# 너는 IT 기업의 사내 메신저(Slack) DB야.
# 개발팀 직원들이 나누는 평범한 일상 대화 및 업무 수다 50줄을 생성해 줘.
# 반드시 아래 CSV 포맷 규칙을 엄격히 지켜서 코드 블록으로만 출력해:
# Date,Time,Sender,Receiver,Message

# 예시:
# 2024-07-29,11:30:00,박신입,최과장,과장님 오늘 점심 제육볶음 어떠신가요?
# """)

# print("\n2️⃣ [법인카드 내역 노이즈 프롬프트]")
# print("""
# 너는 IT 기업의 법인카드 승인 내역 DB야.
# 7월 한 달간 임직원들이 결제한 정상적인 법인카드 내역 50건을 생성해 줘.
# 반드시 아래 CSV 포맷 규칙을 엄격히 지켜서 코드 블록으로만 출력해:
# Date,Time,Card_Owner,Merchant_Name,Amount,Category,Status

# 예시:
# 2024-07-29,12:40:00,이대리,스타벅스 강남점,14500,식대,승인
# """)

# print("\n3️⃣ [시스템 Access 로그 노이즈 프롬프트]")
# print("""
# 너는 IT 기업의 서버실 출입 및 시스템 Access Log DB야.
# 정상적인 서버 Ping 체크, 시스템 헬스체크 로그 50줄을 생성해 줘.
# 반드시 아래 CSV 포맷 규칙을 엄격히 지켜서 코드 블록으로만 출력해:
# Date,Time,Event_Type,Location,User_Name,IP_Address,Detail_Log

# 예시:
# 2024-07-29,19:15:22,HEALTH_CHECK,Server_Room,System,192.168.1.1,Normal ping check - 200 OK
# """)

import csv

# 구하시던 실제 직장인 톤앤매너의 사내 메신저(Slack) 대용량 CSV 데이터셋
slack_csv_data = [
    ["Date", "Time", "Sender", "Receiver", "Message"],
    ["2026-07-28", "08:52:10", "A대리", "B과장", "과장님 출근하셨나요... 오늘 비 엄청 오네요 ㅠㅠ"],
    ["2026-07-28", "08:55:03", "B과장", "A대리", "어 방금 엘베 탔음. 강남대로 완전 주차장이더라 ㄷㄷ"],
    ["2026-07-28", "08:58:15", "A대리", "B과장", "탕비실에 커피 캡슐 새로 들어온 거 보셨어요?"],
    ["2026-07-28", "09:01:22", "B과장", "A대리", "오 진짜? 디카페인도 들어왔나? 요즘 위가 너무 아파서..."],
    ["2026-07-28", "09:02:40", "A대리", "B과장", "아뇨 팀장님이 자기 드실 에스프레소만 잔뜩 시키셨던데요 ㅋㅋㅋ"],
    ["2026-07-28", "09:05:11", "B과장", "A대리", "하... 내 그럴 줄 알았다 진짜. 법카를 아주 자기 맘대로 쓰시네."],
    ["2026-07-28", "09:30:00", "최과장", "김팀장", "팀장님 어제 요청하신 3분기 인프라 견적서 전달드립니다."],
    ["2026-07-28", "09:35:12", "김팀장", "최과장", "어 확인했고, 서버 비용 부분 10%만 더 깎아보라고 해봐."],
    ["2026-07-28", "10:15:00", "박신입", "A대리", "대리님 지난달 연차 사용 내역 어디서 확인하나요?"],
    ["2026-07-28", "10:16:30", "A대리", "박신입", "HR 포털 로그인해서 마이페이지 - 연차관리 들어가면 돼요!"],
    ["2026-07-28", "10:30:45", "A대리", "B과장", "과장님 오늘 점심 뭐 드실 건가요? 제육 땡기네요."],
    ["2026-07-28", "10:32:10", "B과장", "A대리", "제육 콜. 지하 1층 백반집 갈까? 거기 가 젤 빠르잖아."],
    ["2026-07-28", "10:33:00", "A대리", "B과장", "네 좋아요! 11시 40분에 바로 튀어나가시죠."],
    ["2026-07-28", "11:42:15", "A대리", "B과장", "과장님 튀튀! 1층 엘베 앞입니다."],
    ["2026-07-28", "13:10:05", "B과장", "A대리", "대리님 아까 밥 먹고 오다가 팀장님 마주친 거 봤어?"],
    ["2026-07-28", "13:12:40", "A대리", "B과장", "네 ㅋㅋㅋ 눈 마주칠까 봐 모니터 보는 척했어요."],
    ["2026-07-28", "13:40:11", "김팀장", "이대리", "이대리, 오메가 모델 가중치 검증 작업 어디까지 진행됐나?"],
    ["2026-07-28", "13:42:00", "이대리", "김팀장", "현재 최종 체크포인트 테스트 중입니다. 오늘 저녁 전까지 마무리하겠습니다."],
    ["2026-07-28", "14:20:18", "A대리", "B과장", "과장님 혹시 오전 회의 때 팀장님이 말씀하신 API 명세서 받으셨나요?"],
    ["2026-07-28", "14:25:01", "B과장", "A대리", "아니 나한테 안 줬는데? 또 까먹고 안 올린 거 아냐?"],
    ["2026-07-28", "14:26:33", "A대리", "B과장", "진짜 미치겠네요. 개발팀에서는 빨리 달라고 난리인데..."],
    ["2026-07-28", "14:30:12", "B과장", "A대리", "내가 메신저로 한 번 찔러볼게. 대리님은 일단 하던 거 해."],
    ["2026-07-28", "15:10:00", "최과장", "이대리", "이대리님 혹시 체리 청축 키보드 타건음 너무 크지 않아요? 개발룸에서 소리 다 들리던데 ㅋㅋㅋ"],
    ["2026-07-28", "15:12:05", "이대리", "최과장", "아 죄송합니다 과장님 ㅠㅠ 타건감이 좋아서 쓰는데 살살 치도록 하겠습니다!"],
    ["2026-07-28", "15:45:22", "박신입", "A대리", "대리님... 지라 티켓 승인 요청드렸는데 확인 가능하실까요? ㅠㅠ"],
    ["2026-07-28", "15:47:00", "A대리", "박신입", "지금 상반기 결산 때문에 정신없어서 4시 반에 확인해줄게요!"],
    ["2026-07-28", "16:10:40", "최과장", "B과장", "과장님 혹시 이번 주 금요일 연차 쓰시나요?"],
    ["2026-07-28", "16:12:15", "B과장", "최과장", "네 애 병원 때문에 연차 올렸습니다. 급한 건 메일 주세요."],
    ["2026-07-28", "17:50:00", "A대리", "B과장", "과장님 저 먼저 퇴근해보겠습니다! 내일 봬요."],
    ["2026-07-28", "17:55:20", "B과장", "A대리", "어 고생했어! 난 이것만 마무리하고 갈게~"],
    ["2026-07-28", "18:30:00", "김팀장", "이대리", "이대리 퇴근했나? 오늘 모델 가중치 파일 정리 다 한 거지?"],
    ["2026-07-28", "18:35:10", "이대리", "김팀장", "네 팀장님, 서버에 업로드해 두고 퇴근 준비 중입니다."],
    ["2026-07-28", "21:10:05", "박신입", "최동기", "아 배 아파... 저녁에 먹은 마라탕이 문제인가 ㅠㅠ"],
    ["2026-07-28", "22:15:30", "박신입", "최동기", "속 너무 안 좋아서 집 못 가고 회사 화장실에 갇혀있음..."],
    ["2026-07-28", "23:20:11", "박신입", "최동기", "야 나 사실 서버실 구석에 숨어서 낮잠 자는 중 ㅋㅋ 차라리 이게 편하다"],
    # ★ 스모킹 건 (결정적 단서)
    ["2026-07-28", "23:26:40", "박신입", "최동기", "헉 미친... 누가 들어와서 키보드 치는데 이대리님 청축 체리키보드 소리임 ㄷㄷ"]
]

# 코랩 로컬 환경에 표준 CSV 포맷 파일로 바로 토출
file_name = "2_semistructured_slack.csv"
with open(file_name, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerows(slack_csv_data)

print(f"✅ {file_name} 파일 생성이 완벽하게 완료되었습니다!")

"""Loghub 에서 로그데이터 가져오기

"""

# import random

# # Loghub GitHub의 OpenSSH / Linux Auth 로그 표준 템플릿 데이터 (노이즈)
# loghub_ssh_templates = [
#     "Dec 10 {time} server01 sshd[{pid}]: Accepted password for root from 192.168.1.102 port 54321 ssh2\n",
#     "Dec 10 {time} server01 sshd[{pid}]: pam_unix(sshd:session): session opened for user A대리 by (uid=0)\n",
#     "Dec 10 {time} server01 sshd[{pid}]: Failed password for invalid user admin from 192.168.1.200 port 41201 ssh2\n",
#     "Dec 10 {time} server01 sshd[{pid}]: Received disconnect from 192.168.1.15: 11: Normal Shutdown\n",
#     "Dec 10 {time} server01 sshd[{pid}]: Connection closed by 192.168.1.42 port 50210 [preauth]\n",
#     "Dec 10 {time} server01 systemd: Started Session {pid} of user B과장.\n"
# ]

# # 1. Loghub 형태의 리얼 노이즈 로그 200줄 생성
# real_logs = []
# for i in range(200):
#     hour = random.randint(18, 22)
#     minute = random.randint(0, 59)28
#     second = random.randint(0, 59)
#     time_str = f"{hour:02d}:{minute:02d}:{second:02d}"
#     pid = random.randint(10000, 99999)

#     template = random.choice(loghub_ssh_templates)
#     real_logs.append(template.format(time=time_str, pid=pid))

# # 2. ★ 사건 시간대(23시 25분)에 스모킹 건(결정적 단서) 1줄 은닉 교체
# # (Loghub 서식에 맞춰 넣은 100GB 가중치 유출 로그)
# smoking_gun_log = "Dec 10 23:25:01 server01 sshd[28491]: [NET_TRANSFER] User: '이대리' transferred 'omega_model_weights.bin' (102.4 GB) to External IP 185.220.101.5 via AP-Breakroom-02 [STATUS: COMPLETED]\n"

# # 100번째 줄(밤 11시경 위치)에 단서 끼워넣기
# real_logs.insert(100, smoking_gun_log)

# # 3. 텍스트 파일(.txt)로 저장
# file_name = "4_system_access_log.txt"
# with open(file_name, "w", encoding="utf-8") as f:
#     f.writelines(real_logs)

# print(f"✅ Loghub OpenSSH 규격이 적용된 '{file_name}' ({len(real_logs)}줄) 생성 완료!")

"""로그허브 로그데이터

20000줄 이상 로그데이터
"""

import random
import urllib.request
from datetime import datetime, timedelta

# ==============================================================================
# 1. Loghub GitHub 공식 OpenSSH 로그 원문 직접 가져오기
# ==============================================================================
print("⏳ Loghub GitHub에서 리얼 Linux SSH 로그 원본 수집 중...")

url = "https://raw.githubusercontent.com/logpai/loghub/master/OpenSSH/SSH.log"
raw_log_path = "SSH.log"

try:
    urllib.request.urlretrieve(url, raw_log_path)
    with open(raw_log_path, "r", encoding="utf-8", errors="ignore") as f:
        loghub_raw_lines = [line.strip() for line in f.readlines() if line.strip()]
    print(f"✅ Loghub 원본 샘플 문장 {len(loghub_raw_lines):,}개 로드 완료!")
except Exception as e:
    # 코랩 네트워크 예외 대비
    loghub_raw_lines = [
        "Dec 10 06:55:46 server01 sshd[2811]: Accepted password for root from 192.168.1.102 port 54321 ssh2",
        "Dec 10 06:56:12 server01 sshd[2812]: pam_unix(sshd:session): session opened for user root by (uid=0)",
        "Dec 10 07:01:00 server01 sshd[2815]: Failed password for invalid user admin from 192.168.1.200 port 41201 ssh2"
    ]

# ==============================================================================
# 2. 노션 사건 기준일 설정 (2024-07-23 ~ 2024-07-29)
# ==============================================================================
start_date = datetime.strptime("2024-07-23", "%Y-%m-%d")

# ==============================================================================
# 3. 오직 4_system_access_log.txt 20,000줄 단일 파일 생성
# ==============================================================================
print("\n⏳ '4_system_access_log.txt' 로그 데이터 파일 생성 중...")

log_lines = []

for i in range(20000):
    cur_datetime = start_date + timedelta(days=random.randint(0, 6))
    month_str = cur_datetime.strftime("%b") # Jul
    day_num = cur_datetime.day

    hour = random.randint(0, 23)
    minute = random.randint(0, 59)
    second = random.randint(0, 59)
    time_str = f"{hour:02d}:{minute:02d}:{second:02d}"

    # Loghub 원본 문장 치환
    raw_sample = random.choice(loghub_raw_lines)
    parts = raw_sample.split()
    if len(parts) >= 3:
        rest_log = " ".join(parts[3:])
        formatted_log = f"{month_str} {day_num:02d} {time_str} {rest_log}\n"
    else:
        formatted_log = f"{month_str} {day_num:02d} {time_str} {raw_sample}\n"

    log_lines.append(formatted_log)

# ★ 노션 기획안 사건 당일(Jul 29 23:25:01) 위치에 스모킹 건 1줄 주입
smoking_gun_log = "Jul 29 23:25:01 server01 sshd[28491]: [NET_TRANSFER] User: '이대리' transferred 'omega_model_weights.bin' (102.4 GB) to External IP 185.220.101.5 via AP-Breakroom-02 [STATUS: COMPLETED]\n"
log_lines.insert(18000, smoking_gun_log)

# 파일 출력
file_log = "4_system_access_log.txt"
with open(file_log, "w", encoding="utf-8") as f:
    f.writelines(log_lines)

print(f"\n🎉 성공! Loghub 원본 기반의 '{file_log}' ({len(log_lines):,}줄) 단일 텍스트 파일 생성이 완료되었습니다.")

"""법인카드 내역 csv"""

import random
import csv
from datetime import datetime, timedelta

# ==============================================================================
# 1. 3개월치(2024-05-01 ~ 2024-07-29) 날짜 범위 생성
# ==============================================================================
start_date = datetime.strptime("2024-05-01", "%Y-%m-%d")
date_list = [(start_date + timedelta(days=i)).strftime("%Y-%m-%d") for i in range(90)]
TARGET_DATE = "2024-07-29"  # 노션 기획안 사건 당일

print("⏳ 3개월치(1,000줄) 법인카드 결제 내역 CSV 생성 중...")

card_owners = ["김팀장", "이대리", "박신입", "최과장", "정주임", "강사원"]

# 직장인 현실 법인카드 가맹점 & 카테고리 템플릿
merchants = [
    ("스타벅스 강남점", (4500, 18000), "식대"),
    ("투썸플레이스", (5000, 22000), "식대"),
    ("지하 1층 백반집", (9000, 45000), "식대"),
    ("한일관", (15000, 120000), "식대"),
    ("본도시락", (8500, 35000), "식대"),
    ("카카오T 택시", (6800, 32000), "교통비"),
    ("티머니 승차", (1400, 3000), "교통비"),
    ("알파문구", (12000, 85000), "비품구입"),
    ("쿠팡 비품구매", (25000, 150000), "비품구입"),
    ("GS25 강남역점", (3000, 15000), "야식비"),
    ("BHC치킨", (22000, 65000), "야식비")
]

card_rows = [["Transaction_ID", "Date", "Time", "Card_Owner", "Merchant_Name", "Amount", "Category", "Status"]]

# ==============================================================================
# 2. 1,000건의 정상 결제 노이즈 데이터 생성
# ==============================================================================
for i in range(1000):
    tx_id = f"TX_{i+1000:04d}"
    cur_date = random.choice(date_list)

    # 근무 시간 및 야근 시간대 랜덤 조합
    hour = random.choice([8, 9, 11, 12, 13, 15, 18, 19, 20, 21, 22])
    minute = random.randint(0, 59)
    second = random.randint(0, 59)
    time_str = f"{hour:02d}:{minute:02d}:{second:02d}"

    owner = random.choice(card_owners)
    m_name, (min_amt, max_amt), cat = random.choice(merchants)
    amt = random.randint(min_amt // 100, max_amt // 100) * 100  # 100원 단위 정렬

    card_rows.append([tx_id, cur_date, time_str, owner, m_name, str(amt), cat, "승인"])

# ==============================================================================
# 3. ★ 사건 당일(2024-07-29) 핵심 스모킹 건(김팀장 알리바이 격파용) 은닉
# ==============================================================================
smoking_gun_card = [
    ["EV_TX_001", TARGET_DATE, "23:30:45", "김팀장", "강남역 로맨스 룸살롱", "850000", "접대비", "승인"],
    ["EV_TX_002", "2024-07-30", "00:12:00", "김팀장", "카카오T 택시", "24500", "교통비", "승인"]
]

# 950번째 위치(사건 당일 심야)에 주입
card_rows[950:950] = smoking_gun_card

# ==============================================================================
# 4. CSV 파일 저장
# ==============================================================================
file_name = "3_structured_corporate_card.csv"
with open(file_name, "w", newline="", encoding="utf-8") as f:
    csv.writer(f).writerows(card_rows)

print(f"🎉 완료! 3개월치 데이터가 담긴 '{file_name}' ({len(card_rows):,}줄) 파일 생성이 완료되었습니다.")

